storm_code: al092017 # find the right code at https://www.nhc.noaa.gov/gis/archive_besttrack.php?year=2018
storm_name: "Hurricane Harvey"
dates:
  start: '2017-08-25'
  end: '2017-09-02'
bbox: [-100, 22, -80, 34]
projection: "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"
height: 512
width: 1024
precip_cols: ["#FAFBF3", "#F0F8E3", "#D4E9CA", "#BBE0CE", "#B7DAD0", "#B0CCD7", "#A9B8D7", "#A297C2", "#8F6F9E", "#684A77", "#41234D"]
precip_bin: 4 # inches per bin
gage_flood_col: "#175676"
gage_norm_col: "#4BA3C3"
hurricane_col: "orange"
n_intro_frames: 20 # number of frames in the intro animation linking gages to sparklines
frame_delay_cs: 8 # delay between frames of the gif animation. cs = centiseconds = hundredths of a second
sparks:
  xleft: 0.85 # as percentage of figure width
  xright: 0.99 # don't use 1.0 - it causes an error (invalid value specified for graphics parameter "fig")
  ybottom: 0.30 # as percentage of figure height
  ytop: 0.99 # don't use 1.0 - it causes an error (invalid value specified for graphics parameter "fig")

focus_geoms:
  - # U.S. counties
    database: county
  - # U.S. states
    database: state

secondary_geoms:
  - # non-U.S. islands
    database: "mapdata::world2Hires"
    regions: "(?!USA)"
    xlim: [275, 300]
    ylim: [16, 30]
  - # Mexico
    database: "mapdata::worldHires"
    regions: "Mexico"

# Change will cause refetch of entire nhdplus for view_polygon
# This is input to sf::st_simplify on the NHDPlus flowlines that
# are downloaded by the fetcher that uses it. Reduce it if you
# are going to reduce simplification_tolerance_m below it.
# a value of about 30m will have no affect on the data anything
# greater will remove increasingly more curvature from lines.
fetch_simplification_tolerance_m: 500

# Changes only affect river geom process step.
# Coastal threshold controls the drainage area used to limit
# flowlines that terminate at the ocean. Inland threshold
# controls the drainage area used to limit tributary flowlines
# that terminate into other flowlines.
coastal_threshold_sqkm: 1000
inland_threshold_sqkm: 40000
simplification_tolerance_m: 5000
