storm_name: "Henri"
# `storm_code` and `stn_event` can be commented out or deleted if there is not a storm track
storm_code: al082021 # find the right code at https://www.nhc.noaa.gov/gis/archive_besttrack.php?year=2018
stn_event: 310 # Can find code by looking at REST URLs here: https://stn.wim.usgs.gov/STNDataPortal/#
dates:
  start: '2021-08-21 00:00:00'
  end: '2021-08-24 16:00:00'
date_display_tz: "America/New_York" # UTC is assumed for all input and intermediate data; this is the TZ to display on the GIF
frame_step: 1 # hours elapsed between GIF frames

# view, dimensions
bbox: [-80, 36, -60, 43.7]
#bbox: [-78, 39.5, -60, 45] # zoom option centered around MA
projection: "+proj=lcc +lat_1=34.83333333333334 +lat_2=32.5 +lat_0=31.83333333333333 +lon_0=-81 +x_0=609600 +y_0=0 +ellps=GRS80 +units=m +no_defs "
#projection: "+proj=utm +zone=19 +datum=WGS84"
height: 600
width: 1200

# styling
precip_cols: ["#D4E9CAE6", "#BBE0CE",  "#B0CCD7", "#A9B8D7", "#A297C2", "#8F6F9E",  "#41234D"]
precip_bin: 2 # inches per bin
gage_flood_col: "#175676"
gage_line_col: "#3c829c"
gage_norm_col: "#4BA3C3"
gage_out_col: "white"
gage_ltn_col: "#97cbdb" # #aad4e2 # for non-focal stationary gages (ltn = long-term network), to show in outro
gage_stn_col: "#ff7f50" # for non-focal short-term-network (rapid deployment) gages, to show in outro
hurricane_col: "orange"
hurricane_cols: ["#71c633", "#FBC195", "#FB8147", "#EF5F2C", "#C63526", "#6E1B14"]
hurricane_col_names: ["Tropical Storm %s", "Hurricane %s (Cat1)", "Hurricane %s (Cat2)", "Hurricane %s (Cat3)", "Hurricane %s (Cat4)", "Hurricane %s (Cat5)"] # If these change, legend layout may break
storm_line_col: "grey30"
major_river_col: "#1874cd"
gage_river_col: "#5d9ddc"
lake_col: "#EBF6F8"
marsh_col: NA
ocean_col: "#EBF6F8"
legend_text:
  cex: 1.5
  col: "#161616"
  family: ""

timeline_style:
  pt_cex: 0.5
  pt_col: "gray30"
  pt_pch: "|"
  line_cex: 1
  line_lwd: 0.7
  line_lty: 3
  line_col: "gray45"
  font_cex: 1.5
  font_col: "gray30"

storm_line:
  dark_col: "grey10"
  light_col: "grey60"
  tail_length: 45 # n storm point locations behind the current date time to show the tail
  fade_i: 3 # n storm points between the next colored storm points (smaller fade_i = smoother fade)

# introductory animation
intro:
  t_last_start: 5 # last frame in the intro animation when a site should leave its lat/lon (they're staggered)
  n_frames: 20 # number of frames in the intro animation linking gages to sparklines
  elbow_radius: 50000 # radius of the curvature at the elbow of the dot travel path, in 10000ths of degrees
  point_background: "#175676"
  frame_delay_cs: 8 # delay between intro frames. cs = centiseconds = hundredths of a second

frame_delay_cs: 14 # delay between frames of the gif animation DURING storm frames. cs = centiseconds = hundredths of a second

# Image placement for function calls of USGS watermark, legend, datetime, etc..
#  These are fraction of the coordinate space, where 0,0 is bottom left of figure (some stuff is right justified though - legend)
component_placement:
  watermark_x_pos: "left"
  watermark_y_pos: "top"
  datetime:
    # above watermark for now
    x1: 0.005
    y1: 0.85
  legend_x_pos: "left"
  legend_y_pos: "top"
  sparks:
    xleft: 0.67 # as percentage of figure width
    xright: 0.96 # don't use 1.0 - it causes an error (invalid value specified for graphics parameter "fig")
    ybottom: 0.075 # as percentage of figure height
    ytop: 0.82 # top of the first sparkline. spark title goes above. don't use 1.0 - it causes an error (invalid value specified for graphics parameter "fig")
    ytimeline: 0.06 # y location of timeline; this will use xright and xleft from sparks
    ytimeline_text: 0.025 # y location of timeline dates (0.035 below line has worked well)
  outro:
    # outro text & legend roughly, but not exactly, fit where the sparklines were
    xleft: 0.55
    xright: 0.99
    ytop_ltn: 0.6 # top y coordinate of the text and legend for the long-term network
    ytop_stn: 0.85 # top y coordinate of the text and legend for the short-term network
    ytop_more: 0.4 # top y coordinate of the text and URL for where to learn more


ocean_name_placement:
  -
    x1: 0.5
    y1: 0.15
    label: 'Atlantic Ocean'

focus_geoms:
  -
    # U.S. counties
    database: county
  -
    # U.S. states
    database: state

secondary_geoms:
  -
    # non-U.S. islands
    database: "mapdata::world2Hires"
    regions: "(?!USA)"
    xlim: [275, 300]
    ylim: [16, 30]
  -
    # Canada
    database: "mapdata::worldHires"
    regions: "Canada"

cities:
  # parameters for general coloring of the cities
  dot:
    bg: "gray40"
    col: "gray40"
    pch: 5
    cex: 1
  text:
    col: "gray40"
    font: 1
    cex: 1.1
    angle: 330 # angle in radians for position of label relative to dot. pos is computed from angle: 225-315=1, 315-45=4, 45-135=3, 135-225=2
    dist: 0.007 # relative (fraction of window width) distance from dot to label
  pop_min: 500000 # minimum population size of cities to be chosen by default; `custom` will make additions or modifications and `exclude` will make subtractions
  custom:
    # cities to add or modify relative to the maps::us.cities dataset. added cities can use lat/long from us.cities if they are present in us.cities, even if they don't meet the pop_min criterion
    #-
    #  name: "Richmond VA"
    #  text_angle: 170
    #-
    #  name: "Raleigh NC"
    #  text_angle: 170
    #-
    #  name: "Charlotte NC"
    #  text_angle: 170
    #-
    #  name: "Columbia SC"
    #  text_angle: 170
    #-
    #  name: "Savannah GA"
    #  text_angle: 170
    #-
    #  name: "Jacksonville FL"
    #-
    #  name: "Virginia Beach VA"
    #  dot_cex: 0.8
    #  text_cex: 0.8
    #-
    #  name: "Nags Head NC"
    #  lat: 35.9425
    #  long: -75.6228
    #  dot_cex: 0.8
    #  text_cex: 0.8
    #-
    #  name: "New Bern NC"
    #  news: "CBS"
    #  dot_cex: 0.8
    #  text_cex: 0.8
    #  lat: 35.107686
    #  long: -77.051366
    #-
    #  name: "Wilmington NC"
    #  news: "CBS"
    #  dot_cex: 0.8
    #  text_cex: 0.8
    #-
    #  name: "Myrtle Beach SC"
    #  news: "CBS"
    #  lat: 33.6917
    #  long: -78.8875
    #  dot_cex: 0.8
    #  text_cex: 0.8
    #-
    #  name: "Charleston SC"
    #  news: "google/crisismap"
    #  dot_cex: 0.8
    #  text_cex: 0.8
    # UPCOMING ALONG STORM TRACK:
    #-
    #  name: "Knoxville TN"
    #-
    #  name: "Columbus OH"
    #-
    #  name: "Pittsburgh PA"
    #-
    #  name: "New York NY"
    #-
    #  name: "Boston MA"

  exclude:
    - "Knoxville TN"
    - "Richmond VA"
    - "Memphis TN"
    - "Oklahoma City OK"
    - "Columbus OH"
    - "Fort Worth TX"
    - "Dallas TX"
    - "Detroit MI"
    - "Chicago IL"
    - "Baltimore MD"
    - "New York NY"
    - "Philadelphia PA"
    - "Boston MA"
    - "WASHINGTON DC"
    - "Indianapolis IN"
    - "Nashville TN"
    - "Jacksonville FL"

# Only streamorders greater than this will be fetched.
fetch_streamorder: 5

# Only waterbodies greater than this area will be fetched.
fetch_waterbody_areasqkm: 1000

# Changes only affect river geom process step.
# Coastal threshold controls the drainage area used to limit
# flowlines that terminate at the ocean. Inland threshold
# controls the drainage area used to limit tributary flowlines
# that terminate into other flowlines.
coastal_threshold_sqkm: 1000
inland_threshold_sqkm: 40000
simplification_tolerance_m: 1000

# for linear interpolation of stage data: maximum number of hours under which
# gaps in stage data will be interpolated
stage_gap_threshold: 3
